### ISSUE TITLE
运行 log_test.go trace id永远会是system

### ISSUE THREAD

**Issue by reechou** [xiaomeng79/go-log#1]
请问要怎么使用才会像示例中那样显示

> log.Info("test",context.Background())
    //输出日志:{"level":"info","@timestamp":"2018-11-01T15:04:47.079+0800","caller":"go-log/log_test.go:21","msg":"hello world","project":"zap test","trace_id":"3ece70e8f602a46d","parent_id":"5e57855e4f15604c","span_id":"791c3d0180bb66ad"}

**Comment by xiaomeng79** [comment]
不好意思,刚看到,你首先要接入链路跟踪,[opentracing](https://github.com/opentracing/opentracing-go),然后将跟踪信息保存到context`ctx := opentracing.ContextWithSpan(context.Background(), serverSpan)`,你再输出日志的时候就会有`log.Info("test",ctx)`,如果你使用`istio`,需要将请求头里面的跟踪信息拼起来,保存到`context`,见readme

**Comment by xiaomeng79** [comment]
还有问题,再提吧
